[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
SpineOpt = "0d8fc150-4032-4b6e-9540-20efcb304861"
TulipaClustering = "314fac8b-c762-4aa3-9d12-851379729163"
TulipaIO = "7b3808b7-0819-42d4-885c-978ba173db11"
